# =============================================================================
# BAMOE Camel DB2 Kafka Integration - Application Properties
# =============================================================================

# Server
server.port=8080
server.servlet.context-path=/

# DB2 DataSource - BAMOE CASE Table
camel.db2.case.serverName=vmdevtestdboltp02
camel.db2.case.port=60026
camel.db2.case.databaseName=CSE1DV01
camel.db2.case.username=${DB2_USERNAME}
camel.db2.case.password=${DB2_PASSWORD}
camel.db2.case.driverType=4
camel.db2.case.securityMechanism=3
camel.db2.case.sslConnection=true
camel.db2.case.encryptionAlgorithm=0
#For Local
camel.db2.case.sslTrustStoreLocation=C:/Users/ARagunathan/dcss-truststore.jks
#For Container
#camel.db2.case.sslTrustStoreLocation=/app/dcss-truststore.jks

camel.db2.case.sslTrustStorePassword=changeit

# Kafka Broker
# host.containers.internal resolves to the host machine from inside a container
# This allows the Camel container to reach the Kafka container running on the same host
# For Container
kafka.bootstrap.servers=host.containers.internal:9092
# For Local
#kafka.bootstrap.servers=localhost:9092

# Topic for request received and success response events
kafka.bamoe.publish.topic=bamoe-event-publish

# Topic for all error events
kafka.orch.error.topic=orch-engine-error-log

# Kafka Component Global Settings
# acks=all required when retries > 0 to avoid idempotent producer conflict
camel.component.kafka.configuration.acks=all
camel.component.kafka.configuration.retries=2
camel.component.kafka.configuration.delivery.timeout.ms=500
camel.component.kafka.configuration.max.block.ms=500
camel.component.kafka.configuration.request.timeout.ms=500
camel.component.kafka.configuration.retries=0

# Camel Core
camel.springboot.main-run-controller=true

# Logging
logging.level.root=OFF
logging.level.com.example.camel=OFF
logging.level.org.apache.camel=OFF
logging.level.org.springframework=OFF
logging.level.org.apache.http=OFF
logging.level.com.ibm.db2=OFF