# -------- Private API (Remote Machine) --------
private.api.url=http://172.24.31.54:8081/internal/health
private.api.username=private_user
private.api.password=private_pass

# -------- Kafka --------
kafka.bootstrap.servers=172.24.31.6:9092
kafka.topic=bamoedata-topic

# Kafka producer configs (required for idempotent producer)
camel.component.kafka.configuration.acks=all
camel.component.kafka.configuration.retries=3
camel.component.kafka.configuration.delivery.timeout.ms=5000
camel.component.kafka.configuration.max.block.ms=5000

# -------- Camel --------
camel.springboot.main-run-controller=true

# -------- Logging --------
logging.level.org.apache.camel=INFO
